open Assign2

let testing = true

let run cases b = if b then cases () else []

let eval_tests () =
  [
    assert (interp "242" = 242);
    assert (interp "65 + 44" = 109);
    assert (interp "65 * (44 + 4)" = 65 * (44 + 4));
    (* ADD MORE ASSERTIONS *)
    (* The following test cases are generated by ChatGPT *) 
    (* basic sanity *)
    assert (interp "0" = 0);
    assert (interp "00042" = 42);

    (* whitespace edge cases *)
    assert (interp "   3+4   " = 7);
    assert (interp "\n\t5\t*\n(  2 + 3 ) " = 25);

    (* precedence traps *)
    assert (interp "1 + 2 * 3 + 4" = 11);
    assert (interp "1 * 2 + 3 * 4" = 14);
    assert (interp "10 - 2 * 3" = 4);
    assert (interp "10 - 6 / 3" = 8);

    (* associativity edge cases *)
    assert (interp "20 - 5 - 3" = 12);      (* (20 - 5) - 3 *)
    assert (interp "100 / 10 / 2" = 5);     (* (100 / 10) / 2 *)
(* 
    (* deep nesting *)
    assert (interp "((((((1))))))" = 1);
    assert (interp "((2 + 3) * (4 + 5))" = 45);
    assert (interp "((1 + (2 + 3)) * (4 + (5 * 6)))" = 170); *)
(* (* 
    mixed everything *)
    assert (interp "3 * (2 + 4 * (1 + 1))" = 30);
    assert (interp "(8 + 2) * (3 + 7 / (1 + 6))" = 70);

    (* large expression *)
    assert (
      interp "1 + 2 + 3 * 4 + 5 * (6 + 7) - 8 / 2"
      = 1 + 2 + 3 * 4 + 5 * (6 + 7) - 8 / 2
    );

    (* identity / neutral elements *)
    assert (interp "x + 0" = interp "x");   (* if variables exist *)
    assert (interp "5 * 1" = 5);
    assert (interp "5 - 0" = 5);

    (* tricky parentheses *)
    assert (interp "(((((3 + 2))))) * 1" = 5); *)
  ]

let _run_tests =
  if not testing then [] else
    [
      run eval_tests true;
    ]
