open Assign2

let testing = true

let run cases b = if b then cases () else []

let eval_tests () =
  [
    assert (interp "242" = 242);
    assert (interp "65 + 44" = 109);
    assert (interp "65 * (44 + 4)" = 65 * (44 + 4));
    (* ADD MORE ASSERTIONS *)
    (* The following test cases are generated by ChatGPT *) 
    (* basic sanity *)
    assert (interp "0" = 0);
    assert (interp "00042" = 42);

    (* whitespace edge cases *)
    assert (interp "   3+4   " = 7);
    assert (interp "\n\t5\t*\n(  2 + 3 ) " = 25);

    (* precedence traps *)
    assert (interp "1 + 2 * 3 + 4" = 11);
    assert (interp "1 * 2 + 3 * 4" = 14);
    assert (interp "10 - 2 * 3" = 4);
    assert (interp "10 - 6 / 3" = 8);

    (* associativity edge cases *)
    assert (interp "20 - 5 - 3" = 12);      (* (20 - 5) - 3 *)
    assert (interp "100 / 10 / 2" = 5);     (* (100 / 10) / 2 *)


    
    (* subtraction associativity *)
    assert (interp "20 - 5 - 3" = 12);     (* expected: (20 - 5) - 3 *)
    (* if your code returns 18, it's right-associative *)

    assert (interp "10 - 3 - 2 - 1" = 4);
    (* expected: (((10 - 3) - 2) - 1) *)

    (* division associativity *)
    assert (interp "100 / 10 / 2" = 5);
    (* expected: (100 / 10) / 2 *)

    assert (interp "64 / 4 / 2 / 2" = 4);
    (* expected: (((64 / 4) / 2) / 2) *)



    assert (interp "8 - 3 - 2" = 3);    (* (8 - 3) - 2 *)
    assert (interp "8 / 4 / 2" = 1);    (* (8 / 4) / 2 *)

    assert (interp "10 - 3 - 2 - 1" = 4);
    assert (interp "64 / 4 / 2 / 2" = 4);

    (* A3: mixed same-precedence *) 
    assert (interp "20 - 5 + 3" = 18);   (* (20 - 5) + 3 *)
    assert (interp "20 + 5 - 3" = 22);   (* (20 + 5) - 3 *)


    (* A4: mixed precedence + associativity *)
    assert (interp "10 - 2 * 3 - 1" = 3);
    (* (10 - (2 * 3)) - 1 *)

    assert (interp "100 / 10 / 2 * 2" = 10);
    (* ((100 / 10) / 2) * 2 *)

    (* A5: parentheses force correctness *)
    assert (interp "(20 - 5) - 3" = 12);
    assert (interp "20 - (5 - 3)" = 18);   
  ]

let _run_tests =
  if not testing then [] else
    [
      run eval_tests true;
    ]
