open Assign3

let testing = true

let run cases b = if b then cases () else []

let lex_tests () =
  [
    assert (lex "X = 3 + Y" = ["X"; "="; "3"; "+"; "Y"]);
    assert (lex "XX = 3 * YY" = ["XX"; "="; "3"; "*"; "YY"]);
    assert (lex "VAR = 2 + 3" = ["VAR"; "="; "2"; "+"; "3"]);
    (* TODO: add more tests *)
  ]

let eval_tests () =
  [
    assert (eval [("X", 2); ("Y", 3)] ["3"; "+"; "Y"] = 6);
    assert (eval [("X", 4); ("Y", 12)] ["X"; "+"; "Y"] = 16);
    (* TODO: add more tests *)
  ]

let insert_tests () =
  let l = [("X", 4); ("Y", 12); ("ADDXY", 16)] in
  [
    assert (
      List.assoc "X" l = 4
      && List.assoc "X" (insert_uniq "X" 7 l) = 7);
    (* TODO: add more tests *) 
    (* The following test cases are generated by ChatGPT *)
    assert (List.assoc "X" l = 4);
    assert (List.assoc "Y" l = 12);

    assert (List.assoc "X" (insert_uniq "X" 7 l) = 7);
    assert (List.assoc "Y" (insert_uniq "Y" 99 l) = 99);

    assert (
      let l' = insert_uniq "X" 7 l in
      List.length (List.filter (fun (k, _) -> k = "X") l') = 1
    );

    assert (
      let l' = insert_uniq "Z" 42 l in
      List.assoc "Z" l' = 42
    );

    assert (
      let l' = insert_uniq "Z" 42 l in
      List.assoc "X" l' = 4
      && List.assoc "Y" l' = 12
    );

    assert (
      insert_uniq "A" 1 [] = [("A", 1)]
    );

    assert (
      insert_uniq "A" 2 [("A", 1)] = [("A", 2)]
    );
  ]

let _run_tests =
  if not testing then [] else
    [
      run lex_tests true;
      run eval_tests true;
      run insert_tests true;
    ]
